// import React, { Children } from "react";  
// import "./globals.css";
// import Link from "next/link";

// export const metadata = {
//   title:{
//   default: "Ucell",
//   template: '%s | Ucell',
//   },
//   description: "Generated by create next app",
// };

// export default function RootLayout({children}) {
//   return (
//     <html >
//       <body>
//        <nav class="bg-blue-600 h-[10vh]  text-white">
//     <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
//       <div class="flex justify-between items-center h-15">
//         <div class="flex-shrink-0">
//           <p class="text-lg ">MyLogo</p>
//         </div>
//         <div class="hidden md:flex space-x-4    text-center pr-[10vh] items-center   justify-center ">
//           <Link href="/"class="hover:bg-blue-700 px-3 py-2 rounded">Home</Link>
//             <Link href="/About" class="hover:bg-blue-700 px-3 py-2 rounded">About</Link>
//             <Link href="/Servis" class="hover:bg-blue-700 px-3 py-2 rounded">Services</Link>
//             <Link href="/Contact" class="hover:bg-blue-700 px-3 py-2 rounded">Contact</Link>
//         </div>
       
// <input type="search" placeholder="Search..." className="border border-gray-300 rounded-md px-4 py-2  " />

// <div className="flex items-center space-x-4">  
//       <Link href="/Login">
//        <button className=" bg-green-900 rounded-sm  w-20 h-10 ">Login</button>
//       </Link> 
//       <Link href="/Register">
//        <button className="bg-green-900 w-20 h-10 rounded-sm">Register</button>
//       </Link> 
//       </div>
//       </div>
//     </div> 
//   </nav>
// {children}
  
//       <footer class="bg-blue-600 h-[10vh] text-white mt-8">
//           <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
//             <div class="flex justify-between items-center">
//               <p class="text-sm">&copy; 2025 MyCompany. All rights reserved.</p>
//               <div class="flex space-x-4">
//                 <a  class="hover:underline">Privacy Policy</a>
//                 <a  class="hover:underline">Terms of Service</a>
//               </div>
//             </div>
//           </div>
//         </footer> 
 

//       </body>
//     </html>
//   );
// }



import React, { Children } from "react";  
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title:{
  default: "Ucell",
  template: '%s | Ucell',
  },
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html >
      <body>
      <nav className="bg-amber-600 text-white shadow-md p-4">
      <div className="container mx-auto flex justify-between items-center">
        <div className="font-bold text-lg">
          Name
        </div>
        <div className="flex gap-6">
          <Link href="/" className="hover:text-gray-200 font-semibold">
            Home
          </Link>
          <Link href="/category" className="hover:text-gray-200 font-semibold">
            Category
          </Link>
          <Link href="/region" className="hover:text-gray-200 font-semibold">
Region
          </Link>
          <Link href="/neme" className="hover:text-gray-200 font-semibold">
Name
          </Link>
        </div>
      </div>
    </nav>
   
    
    
    {children}

    
    
    
    
    
    
      <footer class="bg-blue-600 h-[10vh] text-white mt-8">
           <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
             <div class="flex justify-between items-center">
               <p class="text-sm">&copy; 2025 MyCompany. All rights reserved.</p>
              <div class="flex space-x-4">
                <a  class="hover:underline">Privacy Policy</a>
                <a  class="hover:underline">Terms of Service</a>
              </div>
            </div>
          </div>
        </footer> 
      
 

      </body>
    </html>
  );
}



