
 import React from 'react';
 export const metadata = {
    title:{
    default: "Contact",   
    template: '%s | Ucell',
    },
    description: "Generated by create next app",
  };
const Contact = () => {
    return (
        <div className="max-w-2xl mx-auto p-6 bg-gray-100 rounded-lg shadow-md">
            <h1 className="text-3xl font-bold text-center mb-6">Contact Us</h1>
            <p className="text-center text-gray-700 mb-6">
                If you have any questions, feel free to reach out to us!
            </p>
            <form className="space-y-4">
                <div>
                    <label htmlFor="name" className="block text-sm font-medium text-gray-700">     Name: </label>
                    <inpu type="text" id="name " name="name require" className="mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" />
                </div>
                <div>
                    <label htmlFor="email" className="block text-sm font-medium text-gray-700">      Email:  </label>
                    <input type="email" id="email" name="email" required className="mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" />
                </div>
                <div>
                    <label htmlFor="message" className="block text-sm font-medium text-gray-700"> Message: </label>
                    <textarea id="message" name="message" required className="mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
                    ></textarea>
                </div>
                <button type="submit" className="w-full bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                >
                    Submit
                </button>
            </form>
        </div>
    );
};

export default Contact;;